version: '3'
includes:
  common: task-templates/docker-task.yml
tasks:
  app:build:
    cmds:
      - task: common:docker:build
        vars:
          SRC_DIR: "app"
          NAME: "app"

  app1:build:
    cmds:
      - task: common:docker:build
        vars:
          SRC_DIR: "app1"
          NAME: "app1"

  app2:build:
    cmds:
      - task: common:docker:build
        vars:
          SRC_DIR: "app2"
          NAME: "app2"
