image: docker:27.0.3

stages:
  - build

build:
  stage: build
  script:
    - apk add bash curl
    - sh -c "$(curl --location https://taskfile.dev/install.sh)" -- -d -b /usr/local/bin
    - export TASK_X_REMOTE_TASKFILES=1
    - task --download -y
    - task app:docker:build_push SRC_DIR=~/todo/app REGISTRY=controlplane:5000 REPOSITORY=app SRC=.
