# https://taskfile.dev

version: '3'

vars:
  AC: Alternating Current
  AG: Azure 'Application Gateway'
  AKA: Also Known As
  AS: Application Server
  ASR: Azure Site Recovery
  CSV: Comma Separated Values (File Format)
  DC: |
     Data Centre
     Direct Current
     Also sometimes referred to as the place Washington D.C. (District of Columbia)
  IEEE: Institute of Electrical and Electronics Engineers
  IETF: Internet Engineering Task Force
  MIP: Microsoft Information Protection
  MIV: max_input_vars (PHP Setting)
  MRW: MaxRequestWorkers (Apache Setting)
  NSG: Azure 'Network Service Gateway'
  OKR: Objectives and Key Results
  RCA: Root Cause Analysis
  RFC: |
     Request for Comments
     Request for Change
  TSV: Tab Separated Values (File Format)
  GREETING: try 'task okr' to see what OKR stands for

tasks:
  default:
    cmds:
      - echo "{{.GREETING}}"
    silent: true
  ac:
    cmds:
      - echo "{{.AC}}"
    silent: true
  ag:
    cmds:
      - echo "{{.AG}}"
    silent: true
  aka:
    cmds:
      - echo "{{.AKA}}"
    silent: true
  as:
    cmds:
      - echo "{{.AS}}"
    silent: true
  asr:
    cmds:
      - echo "{{.ASR}}"
    silent: true
  csv:
    cmds:
      - echo "{{.CSV}}"
    silent: true
  dc:
    cmds:
      - echo "{{.DC}}"
    silent: true
  ieee:
    cmds:
      - echo "{{.IEEE}}"
    silent: true
  ietf:
    cmds:
      - echo "{{.IETF}}"
    silent: true
  mip:
    cmds:
      - echo "{{.MIP}}"
    silent: true
  miv:
    cmds:
      - echo "{{.MIV}}"
    silent: true
  mrw:
    cmds:
      - echo "{{.MRW}}"
    silent: true
  nsg:
    cmds:
      - echo "{{.NSG}}"
    silent: true
  okr:
    cmds:
      - echo "{{.OKR}}"
    silent: true
  rca:
    cmds:
      - echo "{{.RCA}}"
    silent: true
  rfc:
    cmds:
      - echo "{{.RFC}}"
    silent: true
  tsv:
    cmds:
      - echo "{{.TSV}}"
    silent: true
