# https://taskfile.dev

version: '3'

vars:
  MIP: Microsoft Information Protection
  MIV: max_input_vars (PHP Setting)
  MRW: MaxRequestWorkers (Apache Setting)
  OKR: Objectives and Key Results
  RCA: Root Cause Analysis
  RFC: |
     Request for Comments
     Request for Change
  GREETING: try 'task okr' to see what OKR stands for

tasks:
  default:
    cmds:
      - echo "{{.GREETING}}"
    silent: true
  mip:
    cmds:
      - echo "{{.MIP}}"
    silent: true
  miv:
    cmds:
      - echo "{{.MIV}}"
    silent: true
  mrw:
    cmds:
      - echo "{{.MRW}}"
    silent: true
  okr:
    cmds:
      - echo "{{.OKR}}"
    silent: true
  rca:
    cmds:
      - echo "{{.RCA}}"
    silent: true
  rfc:
    cmds:
      - echo "{{.RFC}}"
    silent: true
