# https://taskfile.dev

version: '3'

vars:
  GREETING: Hello, World!

tasks:
  default:
    cmds:
      - echo "{{.GREETING}}"
    silent: true
  msg:
    cmds:
      - 'echo "Message is: {{.MESSAGE}}"'
    vars:
      MESSAGE: '{{ .MESSAGE | default "Testing123" }}'

